# Generated by Django 4.2.7 on 2025-11-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='cesfam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='pacientes.cesfam'),
        ),
    ]
