# Generated by Django 4.2.7 on 2025-11-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad Médico',
                'verbose_name_plural': 'Disponibilidades Médicos',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('medicina_general', 'Medicina General'), ('pediatria', 'Pediatría'), ('ginecologia', 'Ginecología'), ('cardiologia', 'Cardiología'), ('dermatologia', 'Dermatología'), ('traumatologia', 'Traumatología'), ('oftalmologia', 'Oftalmología'), ('otorrinolaringologia', 'Otorrinolaringología'), ('psiquiatria', 'Psiquiatría'), ('nutricion', 'Nutrición')], max_length=50)),
                ('rut_profesional', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
    ]
