# Generated by Django 4.2.7 on 2025-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='rut_profesional',
            field=models.CharField(max_length=50, unique=True, verbose_name='RUT Profesional'),
        ),
    ]
