# Generated by Django 4.2.7 on 2025-11-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medico'),
        ),
    ]
