# Generated by Django 4.2.7 on 2025-11-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('medicos', '0001_initial'),
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('medico', 'fecha', 'hora')},
        ),
    ]
