# Generated by Django 4.2.7 on 2025-11-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0002_initial'),
        ('pacientes', '0001_initial'),
        ('citas', '0003_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='licenciamedica',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.cita'),
        ),
        migrations.AddField(
            model_name='licenciamedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='licenciamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.cita'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='pacientes.paciente'),
        ),
    ]
